import { CheckCircle, QrCode, Repeat, Send } from 'lucide-react';
import type { DocsSection } from '../types';
import { Callout, CodeBlock, MetricCard } from '../ui';
import { GlassCard } from '../../../../shared/components/ui/GlassCard';
import { invoiceCreateLeoCode } from '../examples';

const invoiceCreateStandardExample = `// Create a standard invoice checkout session from the backend
const session = await nullpay.checkout.sessions.create({
  amount: 10,         // 10 USDCX
  currency: 'USDCX',  // CREDITS | USDCX | USAD
  type: 'standard',   // Single settlement → auto-closes on payment
  success_url: 'https://yourapp.com/success?session_id={CHECKOUT_SESSION_ID}',
  cancel_url:  'https://yourapp.com/cancel',
});

// Redirect the buyer to the hosted checkout page
res.redirect(303, session.checkout_url);`;

const invoiceJsonExample = `// nullpay.json — generated by CLI wizard
// Each invoice entry has a hash and salt derived on-chain via the relayer.
{
  "merchant": "aleo1yu926k0jqqzfv06js4jlsxnf2ejah47rfqsxmwfx6tvuxxgvrqpqdlq5y0",
  "generated_at": "2026-03-21T09:10:24.522Z",
  "invoices": [
    {
      "name": "pro-plan",
      "type": "multipay",     // "standard" | "multipay" | "donation"
      "amount": 50,
      "currency": "USDCX",
      "label": "Pro Plan - Monthly",
      "hash": "172487944975353648367...194field",
      "salt": "189135607550214029684...168field"
    },
    {
      "name": "support-campaign",
      "type": "donation",
      "amount": null,          // null = payer chooses amount
      "currency": "ANY",       // ANY = payer picks the token
      "label": "Support the project",
      "hash": "389013768779665896679...623field",
      "salt": "649650755283953756479...428field"
    }
  ]
}`;

const invoiceByNameExample = `// Reference a pre-generated invoice by name from nullpay.json
const session = await nullpay.checkout.sessions.create({
  nullpay_invoice_name: 'pro-plan',  // reads hash, salt, amount, currency from nullpay.json
  success_url: 'https://yourapp.com/success?session_id={CHECKOUT_SESSION_ID}',
  cancel_url:  'https://yourapp.com/cancel',
});`;

export const invoiceTypesSection: DocsSection = {
    id: 'gs-invoice-types',
    group: 'Core Concepts',
    label: 'Invoice Types',
    eyebrow: 'Core Concepts',
    title: 'Invoice types and how they work',
    summary:
        'NullPay supports three distinct invoice types — Standard, Multi-Pay, and Donation — each with different settlement behavior on-chain. Every invoice is identified by a BHP256 hash derived from merchant address, amount, and a random salt. The hash is public; the commercial content is private.',
    content: (
        <div className="space-y-6">
            <div className="grid gap-5 md:grid-cols-3">
                <MetricCard
                    icon={CheckCircle}
                    title="Standard Invoice"
                    description="A one-time fixed-amount payment. Once a single buyer pays and the invoice is settled on-chain, no further payments are accepted. Built for subscriptions, product purchases, and SaaS checkouts."
                />
                <MetricCard
                    icon={Repeat}
                    title="Multi-Pay Invoice"
                    description="A campaign-style invoice that can receive payments from multiple contributors. Useful for crowdfunding, community fundraisers, and scenarios where many payers contribute to a single invoice hash."
                />
                <MetricCard
                    icon={Send}
                    title="Donation Invoice"
                    description="An open-ended invoice where the payer decides both the amount and optionally the token. The merchant sets a label and hash, and contributors can pay any amount they choose."
                />
            </div>

            <GlassCard className="p-6">
                <h3 className="mb-4 text-xl font-bold text-white">Invoice type comparison</h3>
                <div className="overflow-x-auto">
                    <table className="w-full text-sm">
                        <thead>
                            <tr className="border-b border-white/[0.08]">
                                <th className="px-4 py-3 text-left text-[11px] font-black uppercase tracking-widest text-gray-500">Property</th>
                                <th className="px-4 py-3 text-left text-[11px] font-black uppercase tracking-widest text-gray-500">Standard</th>
                                <th className="px-4 py-3 text-left text-[11px] font-black uppercase tracking-widest text-gray-500">Multi-Pay</th>
                                <th className="px-4 py-3 text-left text-[11px] font-black uppercase tracking-widest text-gray-500">Donation</th>
                            </tr>
                        </thead>
                        <tbody className="text-gray-300">
                            <tr className="border-b border-white/[0.04]">
                                <td className="px-4 py-3 font-semibold text-white">On-chain type</td>
                                <td className="px-4 py-3 font-mono text-xs text-orange-300">0u8</td>
                                <td className="px-4 py-3 font-mono text-xs text-orange-300">1u8</td>
                                <td className="px-4 py-3 font-mono text-xs text-orange-300">2u8</td>
                            </tr>
                            <tr className="border-b border-white/[0.04]">
                                <td className="px-4 py-3 font-semibold text-white">Fixed amount</td>
                                <td className="px-4 py-3"><span className="text-emerald-400">Yes</span></td>
                                <td className="px-4 py-3"><span className="text-emerald-400">Yes</span></td>
                                <td className="px-4 py-3"><span className="text-red-400">No (payer chooses)</span></td>
                            </tr>
                            <tr className="border-b border-white/[0.04]">
                                <td className="px-4 py-3 font-semibold text-white">Single settlement</td>
                                <td className="px-4 py-3"><span className="text-emerald-400">Yes (auto-closes)</span></td>
                                <td className="px-4 py-3"><span className="text-red-400">No (stays open)</span></td>
                                <td className="px-4 py-3"><span className="text-red-400">No (stays open)</span></td>
                            </tr>
                            <tr className="border-b border-white/[0.04]">
                                <td className="px-4 py-3 font-semibold text-white">ANY token support</td>
                                <td className="px-4 py-3"><span className="text-red-400">No</span></td>
                                <td className="px-4 py-3"><span className="text-red-400">No</span></td>
                                <td className="px-4 py-3"><span className="text-emerald-400">Yes</span></td>
                            </tr>
                            <tr>
                                <td className="px-4 py-3 font-semibold text-white">Token fixed at creation</td>
                                <td className="px-4 py-3"><span className="text-emerald-400">Yes</span></td>
                                <td className="px-4 py-3"><span className="text-emerald-400">Yes</span></td>
                                <td className="px-4 py-3"><span className="text-red-400">No (if ANY)</span></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </GlassCard>

            <GlassCard className="p-6">
                <h3 className="mb-4 text-xl font-bold text-white">How invoice hashing works</h3>
                <p className="mb-3 text-sm leading-relaxed text-gray-400">
                    Every invoice on NullPay is identified by a <span className="font-semibold text-white">BHP256 hash</span> that commits to the merchant address, the token type, the amount, and a random salt. This hash is the only thing that ever appears on the public Aleo chain. The actual invoice content — amount, who the merchant is, what the charge is for — stays off-chain or in the encrypted metadata.
                </p>
                <p className="mb-4 text-sm leading-relaxed text-gray-400">
                    The hash formula used in the Leo contract is:
                </p>
                <pre className="mb-4 overflow-x-auto rounded-lg border border-white/[0.08] bg-black/50 p-4 font-mono text-xs text-orange-300">
                    invoice_hash = BHP256::hash_to_field(merchant_address) + BHP256::hash_to_field(amount) + BHP256::hash_to_field(salt)
                </pre>
                <div className="grid gap-4 md:grid-cols-2">
                    <div className="rounded-lg border border-white/[0.08] bg-white/[0.02] p-4">
                        <p className="mb-1 text-sm font-bold text-white">What is public on-chain</p>
                        <ul className="mt-2 space-y-1 text-xs leading-relaxed text-gray-400">
                            <li>• The invoice hash (a 254-bit field element)</li>
                            <li>• The settlement record (private to merchant owner)</li>
                            <li>• The payment transaction ID</li>
                            <li>• Expiry height (block number)</li>
                            <li>• Invoice type code (0, 1, or 2)</li>
                        </ul>
                    </div>
                    <div className="rounded-lg border border-white/[0.08] bg-white/[0.02] p-4">
                        <p className="mb-1 text-sm font-bold text-white">What stays private</p>
                        <ul className="mt-2 space-y-1 text-xs leading-relaxed text-gray-400">
                            <li>• Merchant's full Aleo address</li>
                            <li>• Invoice amount and currency</li>
                            <li>• Payer identity</li>
                            <li>• The salt used in hash derivation</li>
                            <li>• Invoice title and memo text</li>
                        </ul>
                    </div>
                </div>
            </GlassCard>

            <GlassCard className="p-6">
                <h3 className="mb-4 text-xl font-bold text-white">Supported tokens</h3>
                <p className="mb-3 text-sm leading-relaxed text-gray-400">
                    The smart contract has separate transition functions for each token type to ensure type-safe, atomic swaps within Aleo's strongly-typed execution model. Merchants and developers should pick the right transition or invoice function at creation time.
                </p>
                <div className="grid gap-4 md:grid-cols-3">
                    {[
                        { token: 'CREDITS', type: '0u8', desc: 'Native Aleo token. Uses credits.aleo::transfer_private. Best for chain-native payments and gas optimization. Amounts in u64 microcredits.' },
                        { token: 'USDCx', type: '1u8', desc: 'A private stablecoin on Aleo. Requires MerkleProof inputs. 6-decimal precision. Good for predictable USD pricing that avoids CREDITS volatility.' },
                        { token: 'USAD', type: '2u8', desc: 'Another private stablecoin on Aleo. Same MerkleProof model as USDCx. Alternative for USD-denominated payments with 6-decimal precision.' },
                    ].map(({ token, type, desc }) => (
                        <div key={token} className="rounded-lg border border-white/[0.08] bg-white/[0.02] p-4">
                            <div className="flex items-center gap-2 mb-2">
                                <code className="text-sm font-bold text-orange-300">{token}</code>
                                <code className="text-[10px] font-mono text-gray-500">type={type}</code>
                            </div>
                            <p className="text-xs leading-relaxed text-gray-400">{desc}</p>
                        </div>
                    ))}
                </div>
                <div className="mt-4 rounded-lg border border-emerald-500/20 bg-emerald-500/5 p-4">
                    <div className="flex items-center gap-2">
                        <p className="text-xs font-bold uppercase tracking-widest text-emerald-300">ANY token (type=3u8)</p>
                        <span className="text-[10px] font-mono text-gray-500">Donation only</span>
                    </div>
                    <p className="mt-2 text-xs leading-relaxed text-gray-400">
                        Donation invoices support <code className="rounded bg-white/5 px-1 py-0.5 text-orange-300">token_type: 3u8 (ANY)</code>, meaning the payer
                        can choose which supported token to use at checkout. The contract verifies the incoming token matches one of the
                        supported types but doesn't enforce a single token upfront. Oracle-backed conversion is not needed for ANY invoices.
                    </p>
                </div>
            </GlassCard>

            <GlassCard className="p-6">
                <h3 className="mb-4 text-xl font-bold text-white">
                    <QrCode className="inline mr-2 h-5 w-5 text-orange-300" />
                    Profile QR and payment links
                </h3>
                <p className="mb-3 text-sm leading-relaxed text-gray-400">
                    Every connected wallet on the NullPay platform has a <span className="font-semibold text-white">Profile QR</span> — a permanent payment link tied to the wallet's invoice hash, salt, and merchant address. Scanning or copying this link opens the NullPay hosted checkout pre-filled for that merchant. It is the fastest way for merchants to accept payments outside of a backend integration.
                </p>
                <div className="grid gap-4 md:grid-cols-2">
                    <div className="rounded-lg border border-white/[0.08] bg-white/[0.02] p-4">
                        <p className="mb-1 text-sm font-bold text-white">Main Profile QR</p>
                        <p className="text-xs leading-relaxed text-gray-400">Uses the main wallet's invoice hash. Initializing it triggers an on-chain transaction to register the hash. Permanent once created. Accessible from nav QR popover or Profile QR page.</p>
                    </div>
                    <div className="rounded-lg border border-white/[0.08] bg-white/[0.02] p-4">
                        <p className="mb-1 text-sm font-bold text-white">Burner Profile QR</p>
                        <p className="text-xs leading-relaxed text-gray-400">Uses the burner wallet's address for full identity separation. Anyone paying this QR has no awareness of the main wallet behind it. Separate tab in the QR popover.</p>
                    </div>
                </div>
            </GlassCard>

            <CodeBlock title="create_invoice — actual Leo implementation" language="leo" code={invoiceCreateLeoCode} />

            <CodeBlock title="Create a checkout session (inline SDK)" language="js" code={invoiceCreateStandardExample} />

            <CodeBlock title="nullpay.json — invoice manifest" language="json" code={invoiceJsonExample} />

            <CodeBlock title="Create a session by invoice name" language="js" code={invoiceByNameExample} />

            <Callout title="nullpay_invoice_name vs. inline params" tone="blue">
                Use <code className="rounded bg-white/10 px-1.5 py-0.5">nullpay_invoice_name</code> when your invoices are
                pre-generated by the CLI and defined in <code className="rounded bg-white/10 px-1.5 py-0.5">nullpay.json</code>.
                Use inline <code className="rounded bg-white/10 px-1.5 py-0.5">amount</code>, <code className="rounded bg-white/10 px-1.5 py-0.5">currency</code>,
                and <code className="rounded bg-white/10 px-1.5 py-0.5">type</code> for fully dynamic, variable-amount checkouts
                that don't need a pre-committed manifest.
            </Callout>
        </div>
    ),
};
