import { CheckCircle, QrCode, Repeat, Send } from 'lucide-react';
import type { DocsSection } from '../types';
import { Callout, CodeBlock, MetricCard } from '../ui';
import { GlassCard } from '../../../../shared/components/ui/GlassCard';

const invoiceCreateStandardExample = `// Standard invoice: one-time, fixed amount, single currency
// Created by the merchant and recorded on-chain via BHP256 hash

// Backend creates a checkout session for a standard invoice
const session = await nullpay.checkout.sessions.create({
  amount: 10,         // 10 USDCX
  currency: 'USDCX', // CREDITS | USDCX | USAD
  success_url: 'https://yourapp.com/success?session_id={CHECKOUT_SESSION_ID}',
  cancel_url:  'https://yourapp.com/cancel',
});

// Redirect the buyer to the hosted checkout page
res.redirect(303, session.checkout_url);`;

const invoiceJsonExample = `// nullpay.json (generated by the CLI wizard)
// Each invoice has a hash and salt derived on-chain
{
  "merchant": "aleo1yu926k0jqqzfv06js4jlsxnf2ejah47rfqsxmwfx6tvuxxgvrqpqdlq5y0",
  "generated_at": "2026-03-21T09:10:24.522Z",
  "invoices": [
    {
      "name": "pro-plan",
      "type": "multipay",    // "standard" | "multipay" | "donation"
      "amount": 50,
      "currency": "USDCX",
      "label": "Pro Plan - Monthly",
      "hash": "172487944975353648367817000692546933725872947260115217528616500920474419194field",
      "salt": "189135607550214029684113079727128581168field"
    },
    {
      "name": "support-campaign",
      "type": "donation",
      "amount": null,        // null = any amount the payer decides
      "currency": "ANY",     // ANY = payer picks the token
      "label": "Support the project",
      "hash": "3890137687796658966791726479363108149438945720273892520625084409687425161623field",
      "salt": "64965075528395375647972437556920314428field"
    }
  ]
}`;

const invoiceByNameExample = `// Use nullpay_invoice_name to reference a pre-generated invoice
const session = await nullpay.checkout.sessions.create({
  nullpay_invoice_name: 'pro-plan',  // reads hash, salt, amount, currency from nullpay.json
  success_url: 'https://yourapp.com/success?session_id={CHECKOUT_SESSION_ID}',
  cancel_url:  'https://yourapp.com/cancel',
});`;

export const invoiceTypesSection: DocsSection = {
    id: 'gs-invoice-types',
    group: 'Core Concepts',
    label: 'Invoice Types',
    eyebrow: 'Core Concepts',
    title: 'Invoice types and how they work',
    summary:
        'NullPay supports three distinct invoice types — Standard, Multi-Pay, and Donation — each encoded differently on-chain. Every invoice is identified by a BHP256 hash derived from the merchant address, amount, currency, and a random salt. The hash is public; the content is private.',
    content: (
        <div className="space-y-6">
            <div className="grid gap-5 md:grid-cols-3">
                <MetricCard
                    icon={CheckCircle}
                    title="Standard Invoice"
                    description="A one-time fixed-amount payment. Once a single buyer pays and the invoice is settled on-chain, no further payments are accepted. Built for subscriptions, product purchases, and SaaS checkouts."
                />
                <MetricCard
                    icon={Repeat}
                    title="Multi-Pay Invoice"
                    description="A campaign-style invoice that can receive payments from multiple contributors. Useful for crowdfunding, community fundraisers, and recurring scenarios where many payers contribute to a single invoice hash."
                />
                <MetricCard
                    icon={Send}
                    title="Donation Invoice"
                    description="An open-ended invoice where the payer decides both the amount and optionally the token. The merchant sets a label and hash, and contributors can pay any amount they choose."
                />
            </div>

            <GlassCard className="p-6">
                <h3 className="mb-4 text-xl font-bold text-white">How invoice hashing works</h3>
                <p className="mb-3 text-sm leading-relaxed text-gray-400">
                    Every invoice on NullPay is identified by a <span className="font-semibold text-white">BHP256 hash</span> that commits to the merchant address, the token type, the amount, and a random salt. This hash is the only thing that ever appears on the public Aleo chain. The actual invoice content — amount, who the merchant is, what the charge is for — stays off-chain or in the encrypted metadata.
                </p>
                <div className="grid gap-4 md:grid-cols-2">
                    <div className="rounded-lg border border-white/[0.08] bg-white/[0.02] p-4">
                        <p className="mb-1 text-sm font-bold text-white">What is public on-chain</p>
                        <ul className="mt-2 space-y-1 text-xs leading-relaxed text-gray-400">
                            <li>• The invoice hash (a 254-bit field element)</li>
                            <li>• The settlement record (private to merchant)</li>
                            <li>• The payment transaction ID</li>
                        </ul>
                    </div>
                    <div className="rounded-lg border border-white/[0.08] bg-white/[0.02] p-4">
                        <p className="mb-1 text-sm font-bold text-white">What stays private</p>
                        <ul className="mt-2 space-y-1 text-xs leading-relaxed text-gray-400">
                            <li>• Merchant's full Aleo address</li>
                            <li>• Invoice amount and currency</li>
                            <li>• Payer identity</li>
                            <li>• The salt used in hash derivation</li>
                        </ul>
                    </div>
                </div>
            </GlassCard>

            <GlassCard className="p-6">
                <h3 className="mb-4 text-xl font-bold text-white">Supported tokens</h3>
                <p className="mb-3 text-sm leading-relaxed text-gray-400">
                    The smart contract has separate transition functions for each token type to ensure type-safe, atomic swaps. Merchants and developers should pick the right one at invoice creation time.
                </p>
                <div className="grid gap-4 md:grid-cols-3">
                    {[
                        { token: 'CREDITS', desc: 'Native Aleo token. Uses the core Aleo Credits program for private transfer. Best for chain-native payments.' },
                        { token: 'USDCx', desc: 'A private stablecoin on Aleo. Denominated in USD equivalent. Good for predictable pricing that avoids CREDITS volatility.' },
                        { token: 'USAD', desc: 'Another private stablecoin on Aleo. Alternative to USDCx for USD-denomination. Follows the same private transfer model.' },
                    ].map(({ token, desc }) => (
                        <div key={token} className="rounded-lg border border-white/[0.08] bg-white/[0.02] p-4">
                            <code className="mb-2 block text-sm font-bold text-orange-300">{token}</code>
                            <p className="text-xs leading-relaxed text-gray-400">{desc}</p>
                        </div>
                    ))}
                </div>
                <div className="mt-4 rounded-lg border border-emerald-500/20 bg-emerald-500/5 p-4">
                    <p className="text-xs font-bold uppercase tracking-widest text-emerald-300">ANY token (Donation only)</p>
                    <p className="mt-1 text-xs leading-relaxed text-gray-400">
                        Donation invoices support <code className="rounded bg-white/5 px-1 py-0.5 text-orange-300">ANY</code> as the currency, meaning the payer can choose which supported token to use at checkout. This is only valid for the donation invoice type.
                    </p>
                </div>
            </GlassCard>

            <GlassCard className="p-6">
                <h3 className="mb-4 text-xl font-bold text-white">
                    <QrCode className="inline mr-2 h-5 w-5 text-orange-300" />
                    Profile QR and payment links
                </h3>
                <p className="mb-3 text-sm leading-relaxed text-gray-400">
                    Every connected wallet on the NullPay platform has a <span className="font-semibold text-white">Profile QR</span> — a permanent payment link tied to the wallet's invoice hash, salt, and merchant address. Scanning or copying this link opens the NullPay hosted checkout pre-filled for that merchant. It is the fastest way for merchants to accept payments outside of a backend integration.
                </p>
                <div className="grid gap-4 md:grid-cols-2">
                    <div className="rounded-lg border border-white/[0.08] bg-white/[0.02] p-4">
                        <p className="mb-1 text-sm font-bold text-white">Main Profile QR</p>
                        <p className="text-xs leading-relaxed text-gray-400">Uses the main wallet's invoice hash. Initializing it triggers an on-chain transaction to register the hash. Permanent once created.</p>
                    </div>
                    <div className="rounded-lg border border-white/[0.08] bg-white/[0.02] p-4">
                        <p className="mb-1 text-sm font-bold text-white">Burner Profile QR</p>
                        <p className="text-xs leading-relaxed text-gray-400">Uses the burner wallet's address for full identity separation. Anyone paying this QR has no awareness of the main wallet behind it.</p>
                    </div>
                </div>
            </GlassCard>


            <CodeBlock title="Create a checkout session (inline)" language="js" code={invoiceCreateStandardExample} />

            <CodeBlock title="nullpay.json — invoice manifest" language="json" code={invoiceJsonExample} />

            <CodeBlock title="Create a session by invoice name" language="js" code={invoiceByNameExample} />

            <Callout title="nullpay_invoice_name vs. inline params" tone="blue">
                Use <code className="rounded bg-white/10 px-1.5 py-0.5">nullpay_invoice_name</code> when your invoices are pre-generated by the CLI and defined in <code className="rounded bg-white/10 px-1.5 py-0.5">nullpay.json</code>. Use inline <code className="rounded bg-white/10 px-1.5 py-0.5">amount</code>, <code className="rounded bg-white/10 px-1.5 py-0.5">currency</code>, and <code className="rounded bg-white/10 px-1.5 py-0.5">type</code> for fully dynamic, variable-amount checkouts that don't need a pre-committed manifest.
            </Callout>
        </div>
    ),
};
