-- Create the merchants table for API keys and webhook configurations
CREATE TABLE IF NOT EXISTS merchants (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    encrypted_aleo_address TEXT NOT NULL,
    secret_key TEXT UNIQUE NOT NULL, -- Used to authenticate the merchant's backend API calls
    webhook_url TEXT,                 -- URL to ping when a payment succeeds
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payment_intents (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    merchant_id UUID REFERENCES merchants(id) ON DELETE CASCADE,
    amount NUMERIC NOT NULL,
    token_type TEXT NOT NULL,         -- 'CREDITS', 'USDCX', 'USAD'
    salt TEXT NOT NULL,               -- The unique salt generated by the Relayer
    invoice_hash TEXT UNIQUE NOT NULL,-- The resulting on-chain invoice hash
    status TEXT NOT NULL DEFAULT 'PENDING', -- 'PENDING', 'PROCESSING', 'SETTLED', 'FAILED'
    success_url TEXT,                 -- Where to redirect the user after successful payment
    cancel_url TEXT,                  -- Where to redirect if they cancel
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_merchant_secret_key ON merchants(secret_key);
CREATE INDEX IF NOT EXISTS idx_intent_merchant_id ON payment_intents(merchant_id);
CREATE INDEX IF NOT EXISTS idx_intent_invoice_hash ON payment_intents(invoice_hash);
CREATE INDEX IF NOT EXISTS idx_intent_status ON payment_intents(status);
