create table if not exists public.telegram_users (
    id bigint generated by default as identity primary key,
    telegram_id_hash text unique,
    telegram_id_ciphertext text,
    username_ciphertext text,
    chat_id_hash text,
    chat_id_ciphertext text,
    aleo_address text,
    aleo_address_client_ciphertext text,
    aleo_address_hash text,
    notifications_enabled boolean not null default true,
    linked_at timestamptz,
    updated_at timestamptz not null default timezone('utc', now()),
    telegram_id bigint,
    username text,
    chat_id bigint
);

alter table public.telegram_users add column if not exists id bigint generated by default as identity;
update public.telegram_users set id = default where id is null;

do $$
begin
    if exists (
        select 1
        from pg_constraint
        where conname = 'telegram_users_pkey'
          and conrelid = 'public.telegram_users'::regclass
    ) then
        alter table public.telegram_users drop constraint telegram_users_pkey;
    end if;
exception when undefined_table then
    null;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'telegram_users_pkey'
          and conrelid = 'public.telegram_users'::regclass
    ) then
        alter table public.telegram_users add constraint telegram_users_pkey primary key (id);
    end if;
exception when undefined_table then
    null;
end $$;

alter table public.telegram_users alter column telegram_id drop not null;
alter table public.telegram_users alter column chat_id drop not null;
alter table public.telegram_users add column if not exists telegram_id_hash text;
alter table public.telegram_users add column if not exists telegram_id_ciphertext text;
alter table public.telegram_users add column if not exists username_ciphertext text;
alter table public.telegram_users add column if not exists chat_id_hash text;
alter table public.telegram_users add column if not exists chat_id_ciphertext text;
alter table public.telegram_users add column if not exists aleo_address text;
alter table public.telegram_users add column if not exists aleo_address_client_ciphertext text;
alter table public.telegram_users add column if not exists aleo_address_hash text;
alter table public.telegram_users add column if not exists notifications_enabled boolean not null default true;
alter table public.telegram_users add column if not exists linked_at timestamptz;
alter table public.telegram_users add column if not exists updated_at timestamptz not null default timezone('utc', now());
alter table public.telegram_users add column if not exists telegram_id bigint;
alter table public.telegram_users add column if not exists username text;
alter table public.telegram_users add column if not exists chat_id bigint;

create unique index if not exists telegram_users_telegram_id_hash_key
    on public.telegram_users (telegram_id_hash);

create index if not exists telegram_users_aleo_address_hash_idx
    on public.telegram_users (aleo_address_hash);

create table if not exists public.telegram_link_sessions (
    id bigint generated by default as identity primary key,
    token_hash text unique,
    telegram_id_hash text not null,
    telegram_id_ciphertext text not null,
    chat_id_hash text not null,
    chat_id_ciphertext text not null,
    username_ciphertext text,
    nonce_ciphertext text not null,
    expires_at timestamptz not null,
    consumed_at timestamptz,
    created_at timestamptz not null default timezone('utc', now()),
    token text,
    telegram_id bigint,
    chat_id bigint,
    nonce text
);

alter table public.telegram_link_sessions add column if not exists id bigint generated by default as identity;
update public.telegram_link_sessions set id = default where id is null;

do $$
begin
    if exists (
        select 1
        from pg_constraint
        where conname = 'telegram_link_sessions_pkey'
          and conrelid = 'public.telegram_link_sessions'::regclass
    ) then
        alter table public.telegram_link_sessions drop constraint telegram_link_sessions_pkey;
    end if;
exception when undefined_table then
    null;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'telegram_link_sessions_pkey'
          and conrelid = 'public.telegram_link_sessions'::regclass
    ) then
        alter table public.telegram_link_sessions add constraint telegram_link_sessions_pkey primary key (id);
    end if;
exception when undefined_table then
    null;
end $$;

alter table public.telegram_link_sessions alter column token drop not null;
alter table public.telegram_link_sessions alter column telegram_id drop not null;
alter table public.telegram_link_sessions alter column chat_id drop not null;
alter table public.telegram_link_sessions alter column nonce drop not null;
alter table public.telegram_link_sessions add column if not exists token_hash text;
alter table public.telegram_link_sessions add column if not exists telegram_id_hash text;
alter table public.telegram_link_sessions add column if not exists telegram_id_ciphertext text;
alter table public.telegram_link_sessions add column if not exists chat_id_hash text;
alter table public.telegram_link_sessions add column if not exists chat_id_ciphertext text;
alter table public.telegram_link_sessions add column if not exists username_ciphertext text;
alter table public.telegram_link_sessions add column if not exists nonce_ciphertext text;
alter table public.telegram_link_sessions add column if not exists token text;
alter table public.telegram_link_sessions add column if not exists telegram_id bigint;
alter table public.telegram_link_sessions add column if not exists chat_id bigint;
alter table public.telegram_link_sessions add column if not exists nonce text;
alter table public.telegram_link_sessions add column if not exists expires_at timestamptz;
alter table public.telegram_link_sessions add column if not exists consumed_at timestamptz;
alter table public.telegram_link_sessions add column if not exists created_at timestamptz not null default timezone('utc', now());

create unique index if not exists telegram_link_sessions_token_hash_key
    on public.telegram_link_sessions (token_hash);

create index if not exists telegram_link_sessions_telegram_id_hash_idx
    on public.telegram_link_sessions (telegram_id_hash);

create index if not exists telegram_link_sessions_expires_at_idx
    on public.telegram_link_sessions (expires_at);

create table if not exists public.telegram_notification_deliveries (
    id bigint generated by default as identity primary key,
    dedupe_key_hash text unique,
    telegram_id_hash text not null,
    telegram_id_ciphertext text not null,
    chat_id_hash text not null,
    chat_id_ciphertext text not null,
    invoice_hash_hash text not null,
    invoice_hash_ciphertext text not null,
    event_type_ciphertext text not null,
    payment_tx_id_ciphertext text,
    delivered_at timestamptz not null default timezone('utc', now()),
    dedupe_key text,
    telegram_id bigint,
    chat_id bigint,
    invoice_hash text,
    event_type text,
    payment_tx_id text
);

alter table public.telegram_notification_deliveries add column if not exists id bigint generated by default as identity;
update public.telegram_notification_deliveries set id = default where id is null;

do $$
begin
    if exists (
        select 1
        from pg_constraint
        where conname = 'telegram_notification_deliveries_pkey'
          and conrelid = 'public.telegram_notification_deliveries'::regclass
    ) then
        alter table public.telegram_notification_deliveries drop constraint telegram_notification_deliveries_pkey;
    end if;
exception when undefined_table then
    null;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'telegram_notification_deliveries_pkey'
          and conrelid = 'public.telegram_notification_deliveries'::regclass
    ) then
        alter table public.telegram_notification_deliveries add constraint telegram_notification_deliveries_pkey primary key (id);
    end if;
exception when undefined_table then
    null;
end $$;

alter table public.telegram_notification_deliveries alter column dedupe_key drop not null;
alter table public.telegram_notification_deliveries alter column telegram_id drop not null;
alter table public.telegram_notification_deliveries alter column chat_id drop not null;
alter table public.telegram_notification_deliveries alter column invoice_hash drop not null;
alter table public.telegram_notification_deliveries alter column event_type drop not null;
alter table public.telegram_notification_deliveries add column if not exists dedupe_key_hash text;
alter table public.telegram_notification_deliveries add column if not exists telegram_id_hash text;
alter table public.telegram_notification_deliveries add column if not exists telegram_id_ciphertext text;
alter table public.telegram_notification_deliveries add column if not exists chat_id_hash text;
alter table public.telegram_notification_deliveries add column if not exists chat_id_ciphertext text;
alter table public.telegram_notification_deliveries add column if not exists invoice_hash_hash text;
alter table public.telegram_notification_deliveries add column if not exists invoice_hash_ciphertext text;
alter table public.telegram_notification_deliveries add column if not exists event_type_ciphertext text;
alter table public.telegram_notification_deliveries add column if not exists payment_tx_id_ciphertext text;
alter table public.telegram_notification_deliveries add column if not exists dedupe_key text;
alter table public.telegram_notification_deliveries add column if not exists telegram_id bigint;
alter table public.telegram_notification_deliveries add column if not exists chat_id bigint;
alter table public.telegram_notification_deliveries add column if not exists invoice_hash text;
alter table public.telegram_notification_deliveries add column if not exists event_type text;
alter table public.telegram_notification_deliveries add column if not exists payment_tx_id text;
alter table public.telegram_notification_deliveries add column if not exists delivered_at timestamptz not null default timezone('utc', now());

create unique index if not exists telegram_notification_deliveries_dedupe_key_hash_key
    on public.telegram_notification_deliveries (dedupe_key_hash);

create index if not exists telegram_notification_deliveries_invoice_hash_hash_idx
    on public.telegram_notification_deliveries (invoice_hash_hash);
